#!/usr/bin/env bash
# =============================================================================
# install_cron.sh
# =============================================================================
# Sets up the daily cron job for sync_cloudflare_to_checkpoint.py on the
# Check Point Management Server.
#
# What this script does:
#   1. Validates that Python 3 and the 'requests' library are available.
#   2. Creates /etc/cp_cloudflare_sync/env containing the credentials and
#      configuration (readable only by root).
#   3. Installs a cron entry that runs the sync at 03:00 every day.
#   4. Optionally runs the script immediately in DRY RUN mode to verify
#      connectivity.
#
# Usage (run as root on the Management Server):
#   chmod +x install_cron.sh
#   ./install_cron.sh
#
# Uninstall:
#   crontab -l | grep -v sync_cloudflare | crontab -
#   rm -rf /etc/cp_cloudflare_sync
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Privilege check ───────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "This installer must be run as root."
    exit 1
fi

# ── Paths ─────────────────────────────────────────────────────────────────────

# Directory where the sync script lives (same directory as this installer)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_SCRIPT="${SCRIPT_DIR}/sync_cloudflare_to_checkpoint.py"

# Secure configuration directory (only root can read it)
CONFIG_DIR="/etc/cp_cloudflare_sync"
ENV_FILE="${CONFIG_DIR}/env"

# Cron wrapper – thin shell that sources the env file before calling Python
CRON_WRAPPER="${SCRIPT_DIR}/run_sync.sh"

# Log file (the Python script also writes here, but cron output goes alongside)
LOG_FILE="${SCRIPT_DIR}/sync_cloudflare.log"

# ── Validate the sync script exists ──────────────────────────────────────────
if [[ ! -f "$SYNC_SCRIPT" ]]; then
    error "sync_cloudflare_to_checkpoint.py not found at: $SYNC_SCRIPT"
    error "Place both files in the same directory and re-run."
    exit 1
fi

# ── Validate Python 3 ────────────────────────────────────────────────────────
info "Checking Python 3 availability…"
PYTHON_BIN=""
for candidate in python3 python3.11 python3.10 python3.9 python3.8; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON_BIN="$(command -v "$candidate")"
        break
    fi
done

if [[ -z "$PYTHON_BIN" ]]; then
    error "Python 3 not found.  Install it with:  yum install python3"
    exit 1
fi

PYTHON_VERSION=$("$PYTHON_BIN" --version 2>&1)
info "Using: $PYTHON_BIN  ($PYTHON_VERSION)"

# ── Validate / install the 'requests' library ────────────────────────────────
info "Checking 'requests' library…"
if ! "$PYTHON_BIN" -c "import requests" 2>/dev/null; then
    warn "'requests' is not installed.  Attempting pip install…"
    if command -v pip3 &>/dev/null; then
        pip3 install --quiet requests
    else
        error "pip3 not found.  Install requests manually: pip3 install requests"
        exit 1
    fi
fi
info "'requests' library is available."

# ── Collect configuration interactively ──────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════"
echo "   Check Point Management Server – Sync Configuration"
echo "══════════════════════════════════════════════════════════"
echo ""

read -rp "Management Server IP or hostname [required]: " CP_HOST
[[ -z "$CP_HOST" ]] && { error "CP_HOST cannot be empty."; exit 1; }

read -rp "Management API port [443]: " CP_PORT
CP_PORT="${CP_PORT:-443}"

read -rp "API admin username [required]: " CP_USER
[[ -z "$CP_USER" ]] && { error "CP_USER cannot be empty."; exit 1; }

read -srp "API admin password [required]: " CP_PASSWORD
echo ""
[[ -z "$CP_PASSWORD" ]] && { error "CP_PASSWORD cannot be empty."; exit 1; }

read -rp "Domain (leave blank for standalone / not MDS): " CP_DOMAIN

read -rp "Policy package name [Standard]: " CP_POLICY
CP_POLICY="${CP_POLICY:-Standard}"

read -rp "Network group name [GRP_Cloudflare_Subnets]: " CP_GROUP
CP_GROUP="${CP_GROUP:-GRP_Cloudflare_Subnets}"

read -rp "Cron schedule (cron syntax) [0 3 * * *  = daily at 03:00]: " CRON_SCHEDULE
CRON_SCHEDULE="${CRON_SCHEDULE:-0 3 * * *}"

echo ""

# ── Write the env file (mode 600 – root only) ─────────────────────────────────
info "Writing configuration to ${ENV_FILE}…"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

cat > "$ENV_FILE" <<EOF
# Cloudflare → Check Point sync configuration
# Generated by install_cron.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# WARNING: This file contains credentials – do NOT share it.

export CP_HOST="${CP_HOST}"
export CP_PORT="${CP_PORT}"
export CP_USER="${CP_USER}"
export CP_PASSWORD="${CP_PASSWORD}"
export CP_DOMAIN="${CP_DOMAIN}"
export CP_POLICY="${CP_POLICY}"
export CP_GROUP="${CP_GROUP}"

# Optional overrides (uncomment and adjust as needed):
# export CP_OBJ_PREFIX="NET_Cloudflare_"
# export CF_API_URL="https://api.cloudflare.com/client/v4/ips"
# export LOG_LEVEL="INFO"
# export DRY_RUN="0"
EOF

chmod 600 "$ENV_FILE"
info "Configuration saved.  Permissions set to 600 (root-only)."

# ── Write the cron wrapper script ─────────────────────────────────────────────
# Cron runs with a minimal environment; this wrapper ensures the env file is
# sourced and that PATH includes common Python locations.
info "Writing cron wrapper to ${CRON_WRAPPER}…"

cat > "$CRON_WRAPPER" <<WRAPPER
#!/usr/bin/env bash
# Cron wrapper for sync_cloudflare_to_checkpoint.py
# Sources credentials from the secure env file, then runs the sync.

# Abort on errors so a partial environment doesn't cause silent bad runs
set -euo pipefail

# Source the secure configuration
# shellcheck source=/dev/null
source "${ENV_FILE}"

# Ensure Python is on PATH (Check Point Gaia shells can be minimal)
export PATH="/usr/local/bin:/usr/bin:/bin:\${PATH}"

# Run the sync; tee output to log so cron captures it AND the log file grows
"${PYTHON_BIN}" "${SYNC_SCRIPT}" 2>&1 | tee -a "${LOG_FILE}"
WRAPPER

chmod 750 "$CRON_WRAPPER"
info "Wrapper script created."

# ── Install the cron entry ────────────────────────────────────────────────────
CRON_MARKER="# sync_cloudflare_to_checkpoint"
CRON_LINE="${CRON_SCHEDULE}  ${CRON_WRAPPER}  ${CRON_MARKER}"

info "Installing cron entry for root…"

# Remove any previous version of this entry to avoid duplicates
( crontab -l 2>/dev/null | grep -v "$CRON_MARKER" ; echo "$CRON_LINE" ) | crontab -

info "Cron entry installed:"
echo ""
echo "    ${CRON_LINE}"
echo ""

# ── Optional immediate dry-run ────────────────────────────────────────────────
echo ""
read -rp "Run a dry-run now to verify connectivity? [Y/n]: " DO_DRYRUN
DO_DRYRUN="${DO_DRYRUN:-Y}"

if [[ "${DO_DRYRUN^^}" == "Y" ]]; then
    info "Running dry-run (no changes will be made)…"
    echo "──────────────────────────────────────────────────────────"
    DRY_RUN=1 bash "$CRON_WRAPPER" || true
    echo "──────────────────────────────────────────────────────────"
    info "Dry-run complete.  Review output above for any errors."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════"
echo "   Installation complete"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "  Script:        ${SYNC_SCRIPT}"
echo "  Config:        ${ENV_FILE}"
echo "  Wrapper:       ${CRON_WRAPPER}"
echo "  Log file:      ${LOG_FILE}"
echo "  Cron schedule: ${CRON_SCHEDULE}"
echo ""
echo "  To run manually:    bash ${CRON_WRAPPER}"
echo "  To run in dry-run:  DRY_RUN=1 bash ${CRON_WRAPPER}"
echo "  To check cron:      crontab -l"
echo "  To uninstall:"
echo "    crontab -l | grep -v sync_cloudflare | crontab -"
echo "    rm -rf ${CONFIG_DIR}"
echo ""
